apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: todolist
    protocol: TCP
  selector:
    app: {{.Values.name}}
